Repository CodeITLab/fit_track_frontend_app, pull requests merged in 2023-12, with the labels that each got.

#3 Css refactor
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/components/navbar.css
  src/assets/css/main.scss
  src/assets/css/views/_homepage.scss
  src/assets/css/views/homepage.css
  src/assets/img/backgrounds/Background4.png
  src/assets/img/backgrounds/Rectangle5.png
  src/assets/img/backgrounds/background6.png
  src/assets/img/backgrounds/background7.png
  src/components/navbar/NavbarComponent.vue
  src/views/HomeView.vue
Labels: Status: Ready To Merge, Status: Ready To Review

#7 Dashboard
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/views/dashboard.css
  src/assets/css/views/homepage.css
  src/assets/img/logos/add-icon.png
  src/assets/img/logos/analitics.png
  src/assets/img/logos/avatar.png
  src/assets/img/logos/home-icon.png
  src/assets/img/logos/log-out.png
  src/assets/img/logos/nutritions.png
  src/assets/img/logos/training.png
  src/components/analytics-component/AnalyticsCard.vue
  src/components/day-card-component/DayCard.vue
  src/components/navbar/NavbarComponent.vue
  src/components/progress-component/ProgressCard.vue
  src/components/side-navbar/SideNavbar.vue
  src/router/index.ts
  src/views/DashboardView.vue
  src/views/HomeView.vue
Labels: Status: Ready For Review

#9 Main menu redesign
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/css/components/navbar.css
  src/assets/css/views/dashboard.css
  src/assets/css/views/homepage.css
  src/components/buttons/ButtonComponent.vue
  src/components/day-card-component/DayCard.vue
  src/components/navbar/NavbarComponent.vue
  src/main.ts
  src/views/DashboardView.vue
  src/views/HomeView.vue
Labels: Type: Feature

#12 Save worukot day card
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/css/components/create-workout-button.css
  src/assets/css/components/create-workout-component.css
  src/assets/css/components/create-workout-modal/create-workout-modal-body.css
  src/assets/css/components/create-workout-modal/create-workout-modal-title.css
  src/assets/css/components/exercise-card-component.css
  src/assets/css/components/side-dash-nav.css
  src/assets/css/views/dashboard.css
  src/assets/css/views/homepage.css
  src/assets/img/icons/delete.png
  src/components/create-workout-component/CreateWorkoutComponent.vue
  src/components/create-workout-component/create-workout-button/CreateWorkoutButton.vue
  src/components/create-workout-component/create-workout-modal/CreateWorkoutModal.vue
  src/components/create-workout-component/create-workout-modal/CreateWorkoutModalBody.vue
  src/components/create-workout-component/create-workout-modal/CreateWorkoutModalTitle.vue
  src/components/dashboard-top-navbar-component/DashboardTopNavbarComponent.vue
  src/components/exercise-card-component/ExerciseCardComponent.vue
  src/components/side-navbar-component/SideNavbarComponent.vue
  src/main.ts
  src/models/IWorkoutModel.ts
  src/store/ModalManager.ts
  src/store/UserData.ts
  src/store/WorkoutData.ts
  src/views/DashboardView.vue
Labels: Type: Feature
